//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElProgreso.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Respuesta
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int PreguntaId { get; set; }
        public string NombreUsuario { get; set; }
        public string Contenido { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
    }
}
